Fix missing types
moleculerjs/moleculer-channels pull request #54
Opened 2022-12-30 15:58 UTC by devcitopia

Linked to this issue https://github.com/moleculerjs/moleculer-channels/issues/53

2023-01-02 17:30 UTC, icebob commented
The problem is that the d.ts files are generated from the source code (jsdoc). So you can't modify the d.ts files directly. We should fix them in jsdoc.

https://github.com/moleculerjs/moleculer-channels/blob/2ddbb9d3ce69e769c0f81d96a2b60193215f0397/package.json#L9

2023-01-03 10:31 UTC, devcitopia commented
You are right I just did a new commit to fix it within the JS code

2023-01-03 16:53 UTC, icebob requested changes

2023-01-03 16:53 UTC, icebob commented on src/index.js
> +module.exports.default = function ChannelsMiddleware(mwOpts) {
It will cause breaking change.

2023-08-06 12:20 UTC, icebob commented
This PR contains many non-relevant changes. Please create a new one only with the relevant changes.

2023-08-06 12:20 UTC, closed without merging